apiVersion: v1
kind: Service
metadata:
  name: k8s-workshop
spec:
  type: NodePort
  selector:
    app: k8s-workshop
  ports:
    - name: http
      targetPort: 80
      port: 80
      nodePort: 30001